language: python
python:
  - "2.7"
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install pytest
addons:
  sonarcloud:
    organization: "montezuma93-github" # the key of the org you chose at step #3
    token:
      secure: CasimirToken # encrypted value of your token
# command to run tests
script:
  - python -m unittest discover
  # other script steps might be done before running the actual analysis
  - sonar-scanner