dist: trusty
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install coverage
addons:
  sonarcloud:
    organization: "montezuma93-github" # the key of the org you chose at step #3
    token:
      secure: "6d0ff832ee5d97268bf61f151dfa6dc1957b3dac" # encrypted value of your token
# command to run tests
script:
  - python tests/test_all_of_the_units.py
  # other script steps might be done before running the actual analysis
  - sonar-scanner